server {
        listen        80;
        server_name  localhost;
        root   "C:/XxSG/Web";
        location / {
            index index.php index.html error/index.html;
            # nginx configuration by winginx.com
            error_page 500 /error.php;
            error_page 404 /error.php;
            error_page 403 /error.php;
            location /user {
              rewrite ^/user/(.*)$ /user.php?page=$1;
              rewrite ^/user/ajax/(.*)$ /user/ajax/$1.php break;
            }
            location /admin@@@@ {
              rewrite ^/admin@@@@/([^\.]+)$ /admin@@@@/index.php?gc=$1;
              rewrite ^/admin@@@@/add-admin.hga$ /admin@@@@/index.php?gc=admin&add=admin;
              rewrite ^/admin@@@@/admin-edit-(.*).hga$ /admin@@@@/index.php?gc=edit&id=$1;
              rewrite ^/admin@@@@/reward-([0-9]+).hga$ /admin@@@@/index.php?gc=reward&id=$1;
              rewrite ^/admin@@@@/bai-viet-edit-([0-9]+).hga$ /admin@@@@/index.php?gc=bai-viet&id=$1;
              rewrite ^/admin@@@@/server-edit-([0-9]+).hga$ /admin@@@@/index.php?gc=server&id=$1;
              rewrite ^/admin@@@@/menu-edit-([0-9]+).hga$ /admin@@@@/index.php?gc=menu&id=$1;
              rewrite ^/admin@@@@/shop-([0-9]+).hga$ /admin@@@@/index.php?gc=shop&id=$1;
              rewrite ^/admin@@@@/del-(.*)-id-(.*).hga$ /admin@@@@/index.php?gc=del&del=$1&id=$2;
              auth_basic "My restricted Area";
              auth_basic_user_file C:\XxSG\Web\admin@@@@\.htpasswd;
            }
            location / {
              rewrite ^/([^\.]+)$ /index.php?p=$1 break;
             rewrite ^/admin@@@@$ /admin@@@@/;
            }
            include C:/XxSG/Web/nginx.htaccess;
            autoindex  off;
        }
        location ~ \.php(.*)$ {
            fastcgi_pass   127.0.0.1:9002;
            fastcgi_index  index.php;
            fastcgi_split_path_info  ^((?U).+\.php)(/?.+)$;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            fastcgi_param  PATH_INFO  $fastcgi_path_info;
            fastcgi_param  PATH_TRANSLATED  $document_root$fastcgi_path_info;
            include        fastcgi_params;
        }
}
